#!/bin/sh

if test -e "$HOME"/.config/ublue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "10"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "15"

echo "# Installing Steam"
/usr/bin/flatpak install --user --noninteractive flathub com.valvesoftware.Steam
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Steam Failed"
        exit 1
fi
echo "20"

echo "# Installing VLC"
/usr/bin/flatpak install --user --noninteractive flathub org.videolan.VLC
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing VLC Failed"
        exit 1
fi
echo "25"

echo "# Installing Snes9x"
/usr/bin/flatpak install --user --noninteractive flathub com.snes9x.Snes9x
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Snes9x Failed"
        exit 1
fi
echo "30"

echo "# Installing Nestopia"
/usr/bin/flatpak install --user --noninteractive flathub ca._0ldsk00l.Nestopia
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Nestopia Failed"
        exit 1
fi
echo "35"

echo "# Installing Minecraft"
/usr/bin/flatpak install --user --noninteractive flathub com.mojang.Minecraft
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Minecraft Failed"
        exit 1
fi
echo "40"

echo "# Installing Bottles"
/usr/bin/flatpak install --user --noninteractive flathub com.usebottles.bottles
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Bottles Failed"
        exit 1
fi
echo "45"

echo "# Installing Anydesk"
/usr/bin/flatpak install --user --noninteractive flathub com.anydesk.Anydesk
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Anydesk Failed"
        exit 1
fi
echo "50"

echo "# Installing Heroic"
/usr/bin/flatpak install --user --noninteractive flathub com.heroicgameslauncher.hgl
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Heroic Failed"
        exit 1
fi
echo "55"

echo "# Installing Ferdium"
/usr/bin/flatpak install --user --noninteractive flathub org.ferdium.Ferdium
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Ferdium Failed"
        exit 1
fi
echo "60"

echo "# Installing ProtonUpQT"
/usr/bin/flatpak install --user --noninteractive net.davidotek.pupgui2
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing ProtonUpQT Failed"
        exit 1
fi
echo "65"

echo "# Installing VSCode"
/usr/bin/flatpak install --user --noninteractive com.visualstudio.code
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing VSCode Failed"
        exit 1
fi
echo "70"

echo "# Installing Emacs"
/usr/bin/flatpak install --user --noninteractive org.gnu.emacs
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Emacs Failed"
        exit 1
fi
echo "75"

echo "# Installing appimagepool"
/usr/bin/flatpak install --user --noninteractive io.github.prateekmedia.appimagepool
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing appimagepool Failed"
        exit 1
fi
echo "80"

echo "# Installing Extension Manager"
/usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Extension Manager Failed Failed"
        exit 1
fi
echo "85"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "90"

echo "# Installing Gnome Extensions"

rpm-ostree install -Ay python3-pip
pip3 install gnome-extensions-cli

gnome-extensions-cli install 615
gnome-extensions-cli install 1401
gnome-extensions-cli install 307
gnome-extensions-cli install 1319
gnome-extensions-cli install 4308
gnome-extensions-cli install 2182
gnome-extensions-cli install 4099
gnome-extensions-cli install 4977
gnome-extensions-cli install 517

rpm-ostree install -Ay virt-manager nordvpn microsoft-edge-dev
sudo chmod -R 777 /var/lib/nordvpn
sudo cp rsa-key-1.pub /var/lib/nordvpn/data/
sudo systemctl enable --now nordvpnd

mkdir -p "$HOME"/.local/share/fonts/

curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf -o "$HOME"/.local/share/fonts/MesloLGS_NF_Regular.ttf
curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf -o "$HOME"/.local/share/fonts/MesloLGS_NF_Bold.ttf
curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf -o "$HOME"/.local/share/fonts/MesloLGS_NF_Italic.ttf
curl -L https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf -o "$HOME"/.local/share/fonts/MesloLGS_NF_Bold_Italic.ttf

mkdir -p ~/Applications
cd ~/Applications
curl -L https://github.com/probonopd/go-appimage/releases/download/continuous/appimaged-745-x86_64.AppImage -o appimaged-745-x86_64.AppImage
chmod +x appimaged-745-x86_64.AppImage
./appimaged-745-x86_64.AppImage

curl -L https://github.com/marzeq/xbox-cloud-gaming-electron/releases/download/1.0.20/xbox-cloud-gaming-electron_1.0.20.AppImage -o xbox-cloud-gaming-electron_1.0.20.AppImage


echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/ublue/
touch "$HOME"/.config/ublue/firstboot-done
cp -n /etc/justfile "$HOME"/.justfile

) | 
     
   zenity --progress --title="uBlue Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi